import { Component, OnInit, Input } from '@angular/core';
import { Product } from 'src/app/shared/types/product';
import { Retailer } from "../../core/retailer/types/retailer";

@Component({
  selector: 'app-retailer-stores',
  templateUrl: './retailer-stores.component.html',
  styleUrls: ['./retailer-stores.component.sass']
})
export class RetailerStoresComponent implements OnInit {

  retailerstoreProducts: any[] = [
    {
        "categoryImageUrl": "../../../assets/category-images/banana_seda.png",
        "categoryName": "Platano",
        "typeImageUrl": "../../../assets/category-images/banana_seda.png", 
        "typeName": "Seda",
        "currency": "PEN",
        "price": 2.5,
        "isSmallSize": true,
        "isMediumSize": true,
        "isBigSize": false,
        "isKilo": true,
        "isUnit": false,
        "isOrganic": true,
        "isSeasonal": true,
        "isMaturityDetails": true,
        "maturityImageUrl": "../../../assets/maturity-images/banana_inmature.png",
        "maturityName": "Inmaduro",
        "maturityInfo": "🍏",
        "maturityEatIn": "7 días",
        "maturityLastFor": "+10 dias"
    },
    {
        "categoryImageUrl": "../../../assets/category-images/banana_seda.png",
        "categoryName": "Platano",
        "typeImageUrl": "../../../assets/category-images/banana_seda.png", 
        "typeName": "Seda",
        "currency": "PEN",
        "price": 2.6,
        "isSmallSize": true,
        "isMediumSize": true,
        "isBigSize": true,
        "isKilo": true,
        "isUnit": true,
        "isOrganic": true,
        "isSeasonal": true,
        "isMaturityDetails": true,
        "maturityImageUrl": "../../../assets/maturity-images/banana_semi_inmature.png",
        "maturityName": "Semi maduro",
        "maturityInfo": "🍏",
        "maturityEatIn": "6 días",
        "maturityLastFor": "+7 dias"
    },
    {
        "categoryImageUrl": "../../../assets/category-images/banana_seda.png",
        "categoryName": "Platano",
        "typeImageUrl": "../../../assets/category-images/banana_seda.png", 
        "typeName": "Seda",
        "currency": "PEN",
        "price": 2.7,
        "isSmallSize": false,
        "isMediumSize": true,
        "isBigSize": false,
        "isKilo": false,
        "isUnit": false,
        "isOrganic": false,
        "isSeasonal": true,
        "isMaturityDetails": true,
        "maturityImageUrl": "../../../assets/maturity-images/banana_mature.png",
        "maturityName": "Maduro",
        "maturityInfo": "🍏",
        "maturityEatIn": "3 días",
        "maturityLastFor": "+5 dias"
    },
    {
        "categoryImageUrl": "../../../assets/category-images/banana_seda.png",
        "categoryName": "Platano",
        "typeImageUrl": "../../../assets/category-images/banana_seda.png", 
        "typeName": "Seda",
        "currency": "PEN",
        "price": 2.8,
        "isSmallSize": false,
        "isMediumSize": true,
        "isBigSize": false,
        "isKilo": false,
        "isUnit": false,
        "isOrganic": false,
        "isSeasonal": true,
        "isMaturityDetails": true,
        "maturityImageUrl": "../../../assets/maturity-images/banana_comer_ya.png",
        "maturityName": "Comer ya",
        "maturityInfo": "🍏",
        "maturityEatIn": "1 día",
        "maturityLastFor": "+4 dias"
    },
    {
        "categoryImageUrl": "../../../assets/category-images/banana_isla.png",
        "categoryName": "Platano",
        "typeImageUrl": "../../../assets/category-images/banana_isla.png", 
        "typeName": "Isla",
        "currency": "PEN",
        "price": 3.5,
        "isSmallSize": true,
        "isMediumSize": true,
        "isBigSize": false,
        "isKilo": true,
        "isUnit": false,
        "isOrganic": true,
        "isSeasonal": false,
        "isMaturityDetails": true,
        "maturityImageUrl": "../../../assets/maturity-images/banana_mature.png",
        "maturityName": "Maduro",
        "maturityInfo": "🍏",
        "maturityEatIn": "3 días",
        "maturityLastFor": "+4 dias"
    },
    {
        "categoryImageUrl": "../../../assets/category-images/banana_isla.png",
        "categoryName": "Platano",
        "typeImageUrl": "../../../assets/category-images/banana_isla.png", 
        "typeName": "Isla",
        "currency": "PEN",
        "price": 3.6,
        "isSmallSize": false,
        "isMediumSize": true,
        "isBigSize": false,
        "isKilo": false,
        "isUnit": false,
        "isOrganic": false,
        "isSeasonal": false,
        "isMaturityDetails": true,
        "maturityImageUrl": "../../../assets/maturity-images/banana_comer_ya.png",
        "maturityName": "Comer ya",
        "maturityInfo": "🍏",
        "maturityEatIn": "1 día",
        "maturityLastFor": "+4 dias"
    },
    {
        "categoryImageUrl": "../../../assets/category-images/banana_bizcocho.png",
        "categoryName": "Platano",
        "typeImageUrl": "../../../assets/category-images/banana_bizcocho.png", 
        "typeName": "Bizcocho",
        "currency": "PEN",
        "price": 4.5,
        "isSmallSize": true,
        "isMediumSize": true,
        "isBigSize": false,
        "isKilo": true,
        "isUnit": false,
        "isOrganic": true,
        "isSeasonal": true,
        "isMaturityDetails": true,
        "maturityImageUrl": "../../../assets/maturity-images/banana_comer_ya.png",
        "maturityName": "Comer ya",
        "maturityInfo": "🍏",
        "maturityEatIn": "1 días",
        "maturityLastFor": "+2 dias"
    }
  ]

  DATA: any = {
    username : "Keyla",
    password: "demo",
    email: "keyla@gmail.com",
    phoneNumber: "8348984",
    store: {
      name: "La tienda de Keyla",
      imgUrl: "../../../assets/fruit-images/fruits_portal_img.jpg",
      isDeliveryService: true,
      isPickUpService: true,
      deliveryInfo: "12 hrs - 15 hrs",
      pickUpInfo: "09 hrs - 13 hrs",
      address: {
        streetName: "Belisario Suares",
        streetnumber: "167",
        city: "Lima",
        department: "LIM",
        country: "PE",
        reference: "reference XYZ",
        details: "details XYZ"
      }
    },
    storeProducts: [
      {
          "categoryImageUrl": "../../../assets/category-images/banana_seda.png",
          "categoryName": "Platano",
          "typeImageUrl": "../../../assets/category-images/banana_seda.png", 
          "typeName": "Seda",
          "currency": "PEN",
          "price": 2.5,
          "isSmallSize": true,
          "isMediumSize": true,
          "isBigSize": false,
          "isKilo": true,
          "isUnit": false,
          "isOrganic": true,
          "isSeasonal": true,
          "isMaturityDetails": true,
          "maturityImageUrl": "../../../assets/maturity-images/banana_inmature.png",
          "maturityName": "Inmaduro",
          "maturityInfo": "🍏",
          "maturityEatIn": "7 días",
          "maturityLastFor": "+10 dias"
      },
      {
          "categoryImageUrl": "../../../assets/category-images/banana_seda.png",
          "categoryName": "Platano",
          "typeImageUrl": "../../../assets/category-images/banana_seda.png", 
          "typeName": "Seda",
          "currency": "PEN",
          "price": 2.6,
          "isSmallSize": true,
          "isMediumSize": true,
          "isBigSize": true,
          "isKilo": true,
          "isUnit": true,
          "isOrganic": true,
          "isSeasonal": true,
          "isMaturityDetails": true,
          "maturityImageUrl": "../../../assets/maturity-images/banana_semi_inmature.png",
          "maturityName": "Semi maduro",
          "maturityInfo": "🍏",
          "maturityEatIn": "6 días",
          "maturityLastFor": "+7 dias"
      },
      {
          "categoryImageUrl": "../../../assets/category-images/banana_seda.png",
          "categoryName": "Platano",
          "typeImageUrl": "../../../assets/category-images/banana_seda.png", 
          "typeName": "Seda",
          "currency": "PEN",
          "price": 2.7,
          "isSmallSize": false,
          "isMediumSize": true,
          "isBigSize": false,
          "isKilo": false,
          "isUnit": true,
          "isOrganic": false,
          "isSeasonal": true,
          "isMaturityDetails": true,
          "maturityImageUrl": "../../../assets/maturity-images/banana_mature.png",
          "maturityName": "Maduro",
          "maturityInfo": "🍏",
          "maturityEatIn": "3 días",
          "maturityLastFor": "+5 dias"
      },
      {
          "categoryImageUrl": "../../../assets/category-images/banana_seda.png",
          "categoryName": "Platano",
          "typeImageUrl": "../../../assets/category-images/banana_seda.png", 
          "typeName": "Seda",
          "currency": "PEN",
          "price": 2.8,
          "isSmallSize": false,
          "isMediumSize": true,
          "isBigSize": false,
          "isKilo": true,
          "isUnit": false,
          "isOrganic": false,
          "isSeasonal": true,
          "isMaturityDetails": true,
          "maturityImageUrl": "../../../assets/maturity-images/banana_comer_ya.png",
          "maturityName": "Comer ya",
          "maturityInfo": "🍏",
          "maturityEatIn": "1 día",
          "maturityLastFor": "+4 dias"
      },
      {
          "categoryImageUrl": "../../../assets/category-images/banana_isla.png",
          "categoryName": "Platano",
          "typeImageUrl": "../../../assets/category-images/banana_isla.png", 
          "typeName": "Isla",
          "currency": "PEN",
          "price": 3.5,
          "isSmallSize": true,
          "isMediumSize": true,
          "isBigSize": false,
          "isKilo": true,
          "isUnit": false,
          "isOrganic": true,
          "isSeasonal": false,
          "isMaturityDetails": true,
          "maturityImageUrl": "../../../assets/maturity-images/banana_mature.png",
          "maturityName": "Maduro",
          "maturityInfo": "🍏",
          "maturityEatIn": "3 días",
          "maturityLastFor": "+4 dias"
      },
      {
          "categoryImageUrl": "../../../assets/category-images/banana_isla.png",
          "categoryName": "Platano",
          "typeImageUrl": "../../../assets/category-images/banana_isla.png", 
          "typeName": "Isla",
          "currency": "PEN",
          "price": 3.6,
          "isSmallSize": false,
          "isMediumSize": true,
          "isBigSize": false,
          "isKilo": false,
          "isUnit": false,
          "isOrganic": false,
          "isSeasonal": false,
          "isMaturityDetails": true,
          "maturityImageUrl": "../../../assets/maturity-images/banana_comer_ya.png",
          "maturityName": "Comer ya",
          "maturityInfo": "🍏",
          "maturityEatIn": "1 día",
          "maturityLastFor": "+4 dias"
      },
      {
          "categoryImageUrl": "../../../assets/category-images/banana_bizcocho.png",
          "categoryName": "Platano",
          "typeImageUrl": "../../../assets/category-images/banana_bizcocho.png", 
          "typeName": "Bizcocho",
          "currency": "PEN",
          "price": 4.5,
          "isSmallSize": true,
          "isMediumSize": true,
          "isBigSize": false,
          "isKilo": true,
          "isUnit": false,
          "isOrganic": true,
          "isSeasonal": true,
          "isMaturityDetails": true,
          "maturityImageUrl": "../../../assets/maturity-images/banana_comer_ya.png",
          "maturityName": "Comer ya",
          "maturityInfo": "🍏",
          "maturityEatIn": "1 días",
          "maturityLastFor": "+2 dias"
      }
    ]
  }

  public retailer: Retailer = new Retailer().deserialize(this.DATA); 

  constructor() { }

  ngOnInit(): void {
  }


}
